/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.16.                           *
*        Compiled Jun  4 2012, 15:48:30                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: segger                                                *
* Dimensions:  100 * 47                                              *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorssegger[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palsegger = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &Colorssegger[0]
};

static GUI_CONST_STORAGE unsigned char acsegger[] = {
  XX______, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, __XX____,
  X_______, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ___X____,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X__X____,
  __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXX__, XXXXXXXX, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXX__, _XXXXXXX, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXX__, __XXXXXX, X___XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXXX_, ___XXXXX, X____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXXXX, ___XXXXX, XX___XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXXXX, X___XXXX, XXX___XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXXXX, X____XXX, XXX____X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXXXX, XX___XXX, XXXX___X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXXXX, XXX___XX, XXXXX___, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXXXX, XXXX___X, XXXXXX__, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXX_XX, XXXX____, XXXXXX__, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXX__X, XXXXX___, XXXXXXX_, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXX__X, XXXXXX__, _XXXXXXX, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXX___, XXXXXXX_, __XXXXXX, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXX___, _XXXXXX_, ___XXXXX, X_______, ________, ________, ________, ________, ________, ________, ________, _____XXX, XX______,
  __XXX___, __XXXXXX, ___XXXXX, XX______, ________, ________, ________, ________, ________, ________, ________, ______XX, XX______,
  __XXX___, __XXXXXX, X___XXXX, XXX_____, ________, ________, ________, ________, ________, ________, ________, _____XXX, XX______,
  __XXX___, ___XXXXX, X____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXX___, __XXXXXX, X___XXXX, XXX_____, ________, ________, ________, ________, ________, ________, ________, _____XXX, XX______,
  __XXX___, __XXXXXX, ___XXXXX, XX______, ________, ________, ________, ________, ________, ________, ________, ______XX, XX______,
  __XXX___, _XXXXXX_, ___XXXXX, X_______, ________, ________, ________, ________, ________, ________, ________, _____XXX, XX______,
  __XXX___, XXXXXXX_, __XXXXXX, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXX__X, XXXXXX__, _XXXXXXX, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXX__X, XXXXX___, _XXXXXX_, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXX_XX, XXXX____, XXXXXX__, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXXXX, XXXX___X, XXXXXX__, _XXXXX__, ____XXXX, _______X, XXXX____, _XXXXXXX, _____XXX, XX______, _XXX____, ___XXXXX, XX______,
  __XXXXXX, XXX___XX, XXXXX___, XXXXX___, XX___XX_, _______X, XX______, __XXXX__, ______XX, X_______, _XX_____, ____XXXX, XX______,
  __XXXXXX, XX____XX, XXXX___X, XXXXX__X, XXX__XX_, __XXXXXX, XX__XXXX, ___XX___, XXXX___X, X___XXXX, XXX___XX, XX__XXXX, XX______,
  __XXXXXX, X____XXX, XXX____X, XXXXX___, XXXXXXX_, __XXXXXX, X__XXXXX, XXXXX__X, XXXXXXXX, X___XXXX, XXX___XX, XX__XXXX, XX______,
  __XXXXXX, X___XXXX, XXX___XX, XXXXXX__, ____XXX_, _______X, X__XXXXX, XXXXX__X, XXXXXXXX, X_______, _XX_____, ____XXXX, XX______,
  __XXXXXX, ___XXXXX, XX___XXX, XXXXXXXX, _____XX_, __XXXXXX, X__XXXX_, ___XX__X, XXX____X, X___XXXX, XXX_____, ___XXXXX, XX______,
  __XXXXX_, ___XXXXX, X____XXX, XXXXXXXX, XXX___X_, __XXXXXX, X___XXXX, X__XX___, XXXXX__X, X___XXXX, XXX___XX, XX__XXXX, XX______,
  __XXXXX_, __XXXXXX, X___XXXX, XXXXX__X, XXX__XX_, __XXXXXX, XX__XXXX, ___XXX__, XXXX___X, X___XXXX, XXX___XX, XX__XXXX, XX______,
  __XXXX__, _XXXXXXX, ___XXXXX, XXXXX___, _____XX_, ________, XX______, ___XXX__, _______X, X_______, __X___XX, XX__XXXX, XX______,
  __XXXX__, XXXXXXXX, __XXXXXX, XXXXXXX_, ____XXXX, _______X, XXXX____, XX_XXXXX, ____XX_X, XX______, _XXX_XXX, XX__XXXX, XX______,
  __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X__X____,
  X_______, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ___X____,
  XX______, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, __XX____
};

GUI_CONST_STORAGE GUI_BITMAP bmsegger = {
  100, /* XSize */
  47, /* YSize */
  13, /* BytesPerLine */
  1, /* BitsPerPixel */
  acsegger,  /* Pointer to picture data (indices) */
  &Palsegger,   /* Pointer to palette */
  NULL
};

/* *** End of file *** */
