/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.16.                           *
*        Compiled Jun  4 2012, 15:48:30                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: silabs                                                *
* Dimensions:  100 * 51                                              *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


#if 0
/*
This palette is included for reference only
As it is saved as device dependent bitmap without color info.
Please note that this bitmap requires the physical palette to be
identical to the palette of the display.
If this does not work out, please convert your bitmap into a DIB */

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorssilabs[] = {
     0x000000,0xFFFFFF
};


#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE Palsilabs = {
  2,	/* number of entries */
  0, 	/* No transparency */
  NULL
};

static GUI_CONST_STORAGE unsigned char acsilabs[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX__XX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXX__XXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X___XXXX, XXXXXXXX, XX______, ________, _____XXX, XXXXXXXX, XXXX___X, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, _XXXXXXX, XXXXXXX_, ________, ________, _______X, XXXXXXXX, XXXX____, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XX_____X, XXXXXXXX, XXXX____, ________, ________, _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX, XX______, ________, ________, ________, XXXXXXXX, XXX_____, __XXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXX___, ___XXXXX, XXXXXXXX, X_______, ________, ________, _______X, XXXXXXXX, XX______, __XXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, ________, ________, ________, ______XX, XXXXXXXX, X_______, ___XXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, X_______, XXXXXXXX, XXXXXXX_, ________, ________, ________, ________, _XXXXX__, ________, ___XXXXX, XXXX____,
  XXXXXXXX, XXXXXXX_, _______X, XXXXXXXX, XXXXXX__, ________, ________, ________, ________, ________, ________, ___XXXXX, XXXX____,
  XXXXXXXX, XXXXXX__, ______XX, XXXXXXXX, XXXXXX__, ________, ___XXXXX, XXXXXXXX, XXXX____, ________, ________, __XXXXXX, XXXX____,
  XXXXXXXX, XXXX____, ______XX, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, __XXXXXX, XXXX____,
  XXXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXX_, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, _XXXXXXX, XXXX____,
  XXXXXXXX, XX______, ______XX, XXXXXXXX, XXXXXXXX, X______X, XX__XXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, _XXXXXXX, XXXX____,
  XXXXXXXX, X_______, _______X, XXXXXXXX, XXXXXXXX, XXXXX___, ________, __XXXXXX, XXXXXXXX, XXXXXX__, ________, XXXXXXXX, XXXX____,
  XXXXXXXX, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X___XXXX, XXXXXXXX, XXXXXXX_, _______X, XXXXXXXX, XXXX____,
  XXXXXXXX, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X____XXX, XXXXXXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXXX____,
  XXXXXXX_, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXX_____, ______XX, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XXXX____,
  XXXXXXX_, ________, ________, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXX__, __XXXXXX, XXXXXXXX, XXXX____,
  XXXXXXX_, ________, ______XX, XX______, ________, ________, ________, ______XX, XXXXXXXX, XXXXX___, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXX_, ________, ____XXXX, XXXXXX__, ________, ________, ________, _____XXX, XXXXXXXX, XXX___XX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, ________, ___XXXXX, XXXXX___, ________, ________, ________, ___XXXXX, XXXXXXXX, XX__XXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, ________, __XXXXXX, XXXXX___, ________, ________, ________, __XXXXXX, XXXXXXXX, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, X_______, _XXXXXXX, XXXXX___, ________, ________, ________, XXXXXXXX, XXXXXX_X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XX______, XXXXXXXX, XXXXXX__, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, X_______, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXX___, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXX_, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXX____X, XXXX_XXX, XXX_XXXX, XXX_XXXX, XX___XXX, XX___XXX, XXX_XX_X, XXXXXXXX, XXX_XXXX, XXXX_XXX, XXXX___X, XXX____X, XXXX____,
  XXX_XX_X, XXXX_XXX, XXX_XXXX, XXX_XXXX, XX_X_XXX, XX_X_XXX, XXX__X_X, XXXXXXXX, XXX_XXXX, XXX__XXX, XXXX_X_X, XXX_XX_X, XXXX____,
  XXX_XXXX, XXXX_XXX, XXX_XXXX, XXX_XXXX, XX_XXXXX, XX_X_XXX, XXX__X_X, XXXXXXXX, XXX_XXXX, XXX__XXX, XXXX_X_X, XXX_XXXX, XXXX____,
  XXX__XXX, XXXX_XXX, XXX_XXXX, XXX_XXXX, XX_XXXXX, XX_X_XXX, XXX__X_X, XXXXXXXX, XXX_XXXX, XXX__XXX, XXXX_X_X, XXX__XXX, XXXX____,
  XXXX_XXX, XXXX_XXX, XXX_XXXX, XXX_XXXX, XX_XXXXX, XX_X_XXX, XXX____X, XXXXXXXX, XXX_XXXX, XXX_XXXX, XXXX___X, XXXX__XX, XXXX____,
  XXXXX_XX, XXXX_XXX, XXX_XXXX, XXX_XXXX, XX_XXXXX, XX_X_XXX, XXX_X__X, XXXXXXXX, XXX_XXXX, XXX_X_XX, XXXX_X_X, XXXXX_XX, XXXX____,
  XXXXXX_X, XXXX_XXX, XXX_XXXX, XXX_XXXX, XX_XXXXX, XX_X_XXX, XXX_X__X, XXXXXXXX, XXX_XXXX, XXX_X_XX, XXXX_X_X, XXXXXX_X, XXXX____,
  XXXXXX_X, XXXX_XXX, XXX_XXXX, XXX_XXXX, XX_XXXXX, XX_X_XXX, XXX_X__X, XXXXXXXX, XXX_XXXX, XXX___XX, XXXX_X_X, XXXXXX_X, XXXX____,
  XXX_XX_X, XXXX_XXX, XXX_XXXX, XXX_XXXX, XX_X_XXX, XX_X_XXX, XXX_X__X, XXXXXXXX, XXX_XXXX, XX_XX_XX, XXXX_X_X, XXX_XX_X, XXXX____,
  XXX____X, XXXX_XXX, XXX___XX, XXX_XXXX, XX___XXX, XX___XXX, XXX_X__X, XXXXXXXX, XXX__XXX, XX_XX_XX, XXXX___X, XXX____X, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____
};

GUI_CONST_STORAGE GUI_BITMAP bmsilabs = {
  100, /* XSize */
  51, /* YSize */
  13, /* BytesPerLine */
  1, /* BitsPerPixel */
  acsilabs,  /* Pointer to picture data (indices) */
  &Palsilabs,   /* Pointer to palette */
  NULL
};

/* *** End of file *** */
