/*****************************************************************************
 * @file main_prs_soft_dac.c
 * @brief PRS Demo Application, DAC conversion triggered by software generated PRS signal
 * @author Silicon Labs
 * @version 1.07
 ******************************************************************************
 * @section License
 * <b>(C) Copyright 2014 Silicon Labs, http://www.silabs.com</b>
 *******************************************************************************
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 *
 * DISCLAIMER OF WARRANTY/LIMITATION OF REMEDIES: Silicon Labs has no
 * obligation to support this Software. Silicon Labs is providing the
 * Software "AS IS", with no express or implied warranties of any kind,
 * including, but not limited to, any implied warranties of merchantability
 * or fitness for any particular purpose or warranties against infringement
 * of any proprietary rights of a third party.
 *
 * Silicon Labs will not be liable for any consequential, incidental, or
 * special damages, or any other relief, or for any claim by any third party,
 * arising from your use of this Software.
 *
 ******************************************************************************/

#include "em_device.h"
#include "em_chip.h"
#include "em_cmu.h"
#include "em_dac.h"
#include "em_emu.h"
#include "em_gpio.h"
#include "em_prs.h"

/**************************************************************************//** 
 * @brief  DAC_setup
 * Configures the DAC
 *****************************************************************************/
void DAC_setup(void)
{
  /* Enable necessary clocks */
  CMU_ClockEnable(cmuClock_DAC0, true);

  /* Use default settings */
  DAC_Init_TypeDef init               = DAC_INIT_DEFAULT;
  DAC_InitChannel_TypeDef initChannel = DAC_INITCHANNEL_DEFAULT;
  
  /* Calculate the DAC clock prescaler value that will result in a DAC clock
   * close to 500kHz. Second parameter is zero, if the HFPERCLK value is 0, the
   * function will check what the current value actually is. */
  init.prescale = DAC_PrescaleCalc(500000, 0);
  /* Set reference voltage to Vdd */
  init.reference = dacRefVDD;
  
  /* Enable PRS triggered conversion (channel 5) */
  initChannel.prsEnable = true;
  initChannel.prsSel = dacPRSSELCh5;
  
  /* Initialize DAC and DAC channel 0 */
  DAC_Init(DAC0, &init);
  DAC_InitChannel(DAC0, &initChannel, 0);
  
  /* Enable DAC channel 0, located on pin PB11 */
  DAC_Enable(DAC0, 0, true);
}

/**************************************************************************//**
 * @brief  DAC_WriteData
 * Write DAC conversion value to a defined channel
 *****************************************************************************/
void DAC_WriteData(DAC_TypeDef *dac, uint32_t value, uint8_t ch)
{
  /* Write data output value to the correct register. */
  if (!ch)
  {
    dac->CH0DATA = value;
  }
  else
  {
    dac->CH1DATA = value;
  }
}

/**************************************************************************//**
 * @brief  Main function
 * Main is called from __iar_program_start, see assembly startup file
 *****************************************************************************/
int main(void)
{  
  /* Align different chip revisions */
  CHIP_Init();
    
  /* Enable clock for PRS */
  CMU_ClockEnable(cmuClock_PRS, true);

  /* Initialize DAC */
  DAC_setup();

  /* Calculate output to 0.5 V. */
  uint32_t dacValue;
  dacValue = (uint32_t)((0.5 * 4096) / 3.3);
  
  /* Write the new value to DAC register
     This value will not be output immediately, 
     only when the PRS pulse is generated by
     software */
  DAC_WriteData(DAC0, dacValue, 0);
  
  /* Generate PRS pulse on channel 5 
     by writing 1 to bit 5 (0x20) in
     PRS_SWPULSE register 
     This will trigger the DAC conversion
     and 0.5V can be probed on PB11 */
  PRS_PulseTrigger(0x20);
  
  while(1)
  {
    /* Enter EM1 */ 
    EMU_EnterEM1();
  }
}
